cyralinc/terraform-aws-sidecar-ec2

- README.md
- iam_resources.tf
Get partition, region and account information from deployed resources. This will enable deployments in GovCloud and also prevent errors in deployment pipelines running on AWS that deploys to different AWS accounts. The later does not work as previous version of the code would get the account ID from the caller identity. In this sense, if you run `terraform apply` in account `A` to deploy to account `B`, then the previous code would create IAM permissions referencing account `A`, not account `B` where the resources were actually deployed.
> ENG-7233: Set proper partitions and account ID to IAM policies

- variables_aws.tf
>
[ENG-7488](https://cyralinc.atlassian.net/browse/ENG-7488): Reduce sidecar default instance size
Changed parameters:
-  Default volume size for sidecar instances (from 30GB to 15GB);
> ENG-7488: Reduce sidecar default instance size

- README.md
- ec2_resources.tf
- variables_aws.tf
See [ENG-8228](https://cyralinc.atlassian.net/browse/ENG-8228): Create sidecar template feature to avoid cartesian product in security group rules.
Related PR: [sidecar-templates#896](https://github.com/cyralinc/sidecar-templates/pull/896)
> ENG-8228: Add reduce_security_group_rules_count variable to avoid cartesian product in security group rules

- .gitignore
- README.md
- cloudwatch_resources.tf
- ec2_locals.tf
- ec2_resources.tf
- files/cloud-init-pre.sh.tmpl
- iam_resources.tf
- output.tf
- route53_resources.tf
- secretsmanager_resources.tf
- variables_aws.tf
- variables_sidecar.tf
- versions.tf
- Enable session stickiness in the network load balancer resource
- Add support for cross-account deployments, for the sidecar ca-signed certificate feature.
The scenario is the following: application in account B needs to manage a ca-signed certificate for account A.
This PR enables the above by creating a role and secret resources in account A, where the role gives permission for account B to edit the secret. You must input the AWS account id for account B in the variable `sidecar_certificate_casigned_account_id` for this to happen. If `sidecar_certificate_casigned_account_id` is empty, none of these resources (secret and role) will be created.
Manual cross-account deployment in AWS, verify that secret is created, and is able to be accessed by the ca-signed certificate feature.
Please …
> ENG-7736: Session stickiness and cross-account deployments for ca-signed certificate

- README.md
The README docs were not up to date with the latest changes. Specifically, the variable `sidecar_certificate_lambda_version` was not mentioned.
> ENG-8456: Fix docs

- iam_resources.tf
- lambda_resources.tf
This PR fixes an issue when upgrading sidecar from versions previous to #39 to versions after #39.
Specifically, if `name_prefix` is modified, and the module is upgraded (i.e. `terraform init -upgrade`), when the user runs `terraform apply`, the resource `aws_lambda_invocation.sidecar_created_certificate` was failing to be created, because the lambda function IAM policy was not in place when it tried to access the sidecar-created certificate secret.
To solve this, `depends_on` did not work. I am not sure why. I tried every combination I could imagine. The only thing that worked was the `lifecycle` meta-argument `ignore_changes`. Please see PR modifications for details. This is OK because with the sidecar-created certificate, we don't need to trigger the lambda function again if the lambda …
> ENG-8959: Fix race condition when upgrading sidecar

- README.md
- versions.tf
Resource `aws_lambda_invocation` included recently requires a minimum AWS provider version of `3.73.0`.
> Fix minimum AWS provider requirements

- ec2_locals.tf
- ec2_resources.tf
- files/cloud-init-post.sh.tmpl
- files/cloud-init-pre.sh.tmpl
- variables_sidecar.tf
Update POST route permission so we can use only the private route for the new CPs
> ENG-9286: Deprecate public docker route

- variables_sidecar.tf
**ENG-10517**: Add deprecation note to the `mysql_multiplexed_port` variable
mysql_multiplexed_port is deprecated for sidecars v4.0.0 and later, as the multiplexing state is now
detached from any template configuration.
This variable will eventually be removed from the terraform module in a future release.
Current sidecars should keep working as is.
> ENG-10517: Add deprecation note to the mysql_multiplexed_port variable

- variables_sidecar.tf
ENG-10518: Add deprecation note to the mongodb low/high alloc ports variables
mongodb_port_alloc_range_low and mongodb_port_alloc_range_high are deprecated
for sidecars v3.0.0 and later and will eventually be removed from the terraform module.
Current sidecars should keep working as is.
> ENG-10518: Add deprecation note to the mongodb low/high alloc ports variables

- .gitignore
- README.md
- variables_integrations.tf
For sidecars v4.6+, these inputs will do nothing. They will be removed in the next major release.
> ENG-11522: Deprecate log integration input variables

- README.md
- ec2_resources.tf
- variables_aws.tf
As per title. Change done because both endpoints are now served in a single port, removing the need for two parameters.
Created a sidecar with the new changes and it deployed and was accessible in the port.
> ENG-11847: Merge healthcheck and metrics inbound CIDR fields into a single monitoring inbound cidr

- README.md
- cloudwatch_resources.tf
- ec2_locals.tf
- variables_sidecar.tf
By creating this external variable, users will be able to set the log group name, and the circular dependency that may happen will cease to exist.
This was the problem before:
```
resource "cyral_sidecar" "sidecar" {
name = "my-sidecar"
deployment_method = "terraform"
log_integration_id = cyral_integration_logging.cloudwatch.id
}
resource "cyral_integration_logging" "cloudwatch" {
name = "my-cloudwatch"
cloud_watch {
region = "us-east-1"
group  = module.cyral_sidecar.aws_cloudwatch_log_group_name
stream = "cyral-sidecar"
}
}
module "cyral_sidecar" {
source  = "cyralinc/sidecar-ec2/aws"  
version = "~> 4.0"
sidecar_id      = cyral_sidecar.sidecar.id
...
}
```
And now we can do this:
```
locals {
cloudwatch_log_group_name = "my-log-group"
}
resource "cyral_sidecar" "sidecar" {
name = …
```
> ENG-11888: Add external parameter to name cloudwatch log groups

- files/cloud-init-functions.sh.tmpl
Enables the docker service instead of just starting it so that on instance restarts
the docker services also restart.
Created an instance and restarted it using the UI and `systemctl reboot`, in both cases
the containers started without interference.
> ENG-11901: Enable docker service for instance restarts

- README.md
- ec2_locals.tf
- files/cloud-init-functions.sh.tmpl
- files/cloud-init-pre.sh.tmpl
- variables_sidecar.tf
In this PR we will:
- Add a boolean variable tls_skip_verify to Terraform that will set an environment variable TLS_SKIP_VERIFY=tls-skip-verify (if true) or TLS_SKIP_VERIFY=tls (if false).
We need this to pass this var over to forward-proxy, giving more flexibility in the TLS verification
> ENG-12176: Add parameter to disable TLS certificate verification to sidecar templates

- ec2_resources.tf
- variables_sidecar.tf
The Terraform module for AWS EC2 sidecars should have a consistency to avoid erroring out in case the variable custom_user_data is provided and does not contain all the keys pre, post and pre_sidecar_start.
In case the provided map does not have any of these keys, it will fail in the lookup calls [in this section of code](https://github.com/cyralinc/terraform-aws-sidecar-ec2/blob/main/ec2_resources.tf#L49-L53).
Test:
using  `source = "git@github.com:cyralinc/terraform-aws-sidecar-ec2.git?ref=ENG-12327"` in the module, I tried 
By not declaring the `custom_user_data` it works just fine: (as the default is a correct object)
Using the object:
```
custom_user_data = {
post               = "echo 'post-commands'"
}
```
I created the sidecar and it's working fine:
by converting b64 message we …
> ENG-12327: Add consistency in case of `custom_user_data` variable does not contain all keys

- files/cloud-init-functions.sh.tmpl
Changes to the `load_certs` function to allow for the init script to continue if the certificate secrets have not been created.
> ENG-12832: Making load_certs echo Warning

- README.md
Replaced some relative links by absolute addresses so it won't show a 404 in Terraform Registry.
> Fix broken links in registry docs

- secretsmanager_resources.tf
Avoid the creation of the TLS resources unnecessarily in cases where users are upgrading from old sidecar version that already has a CA or TLS cert.
> ENG:13220: Optionally create TLS resources

- README.md
- ec2_resources.tf
- variables_aws.tf
Add support for additional target groups.
Tested with the following Terraform script:
```hcl
terraform {
required_providers {
cyral = {
source  = "cyralinc/cyral"
version = "~> 4.7"
}
}
}
locals {
control_plane_host = "<SOME_CP>"
pg = {
address = "<SOME_DB>"
port = 5432
}
external_tg_ports = [5433, 5434]
sidecar = {
public_sidecar = true
region = "us-east-1"
vpc_id = ""
subnets = [""]
cloudwatch_log_group_name = "cyral-example-loggroup"
ssh_inbound_cidr = ["0.0.0.0/0"]
db_inbound_cidr = ["0.0.0.0/0"]
monitoring_inbound_cidr = ["0.0.0.0/0"]
dns_hosted_zone_id = ""
dns_name = ""
}
}
provider "aws" {
region = "us-east-1"
}
provider "cyral" {
client_id     = ""
client_secret = ""
control_plane = local.control_plane_host
}
resource "cyral_repository" "pg" {
name = "pgRepo"
type = "postgresql" …
```
> ENG-14157: Add support for additional target groups

- README.md
- cloudwatch_resources.tf
- ec2_locals.tf
- ec2_resources.tf
- iam_resources.tf
- output.tf
- route53_resources.tf
- variables_aws.tf
Add output variables for AWS resources ARNs to improve module's usability.
Tested with the following example:
```hcl
terraform {
required_providers {
cyral = {
source  = "cyralinc/cyral"
version = "~> 4.7"
}
}
}
locals {
control_plane_host = ""
pg = {
address = ""
port = 5432
}
sidecar = {
public_sidecar = true
ports = [5432, 5433, 5434]
vpc_id = ""
subnets = [""]
ssh_inbound_cidr = ["0.0.0.0/0"]
db_inbound_cidr = ["0.0.0.0/0"]
monitoring_inbound_cidr = ["0.0.0.0/0"]
}
}
provider "aws" {
region = "us-east-1"
}
provider "cyral" {
control_plane = local.control_plane_host
}
resource "cyral_repository" "pg" {
name = "pgRepo"
type = "postgresql"
repo_node {
host = local.pg.address
port = local.pg.port
}
}
resource "cyral_sidecar_listener" "pg" {
for_each   = { for p in …
```
> ENG-13935: Add output variables for AWS resources ARNs

- docs/memlim.md
Add version constraints to memory limits docs and highlight values to improve readability.
> Add version constraints to memory limits

- files/cloud-init-pre.sh.tmpl
Fix a character limit issue that causes snowflake deployments to break. We should not expand public certificates anymore as part of the launch template in the next major version of this module (will require a heads up for customer deploying the secrets themselves, though).
> Fix character limit issue

- ec2_resources.tf
Avoid LB recreation when upgrading directly from `v4.4` to `v4.6+`.
> Avoid LB recreation in upgrades from v4.4 or previous

- README.md
- docs/byos.md
- ec2_locals.tf
- files/cloud-init-functions.sh.tmpl
- secretsmanager_resources.tf
- variables_sidecar.tf
Remove unused variables `container_registry_key` and `container_registry_username` that were missed in the first version of the new major.
These removals can be safely released as a patch as there is no use for these variables in the original code in `v5.0.0`.
> Remove unused variables

- README.md
- ec2_locals.tf
- ec2_resources.tf
Update the module to use the latest version of Amazon Linux 2023. This will be released as a `patch` as this was already part of the plan for the major `v5` and has been extensively tested (including performance tests).
> Use lastest version of Amazon Linux 2023
